<?php
declare(strict_types=1);

use FrontEnd\Controllers\LegacyPageController;
use FrontEnd\Controllers\AdminController;
use FrontEnd\Controllers\AcademicoController;
use FrontEnd\Controllers\BeneficiarioController;
use FrontEnd\Controllers\EventoController;
use FrontEnd\Controllers\RelatorioController;
use FrontEnd\Controllers\SystemController;
use FrontEnd\Controllers\QuizzController;

$systemController = new SystemController();
$legacyController = new LegacyPageController($baseUrl, $basePath);
$adminController = new AdminController($baseUrl, $basePath);
$academicoController = new AcademicoController($baseUrl, $basePath);
$beneficiarioController = new BeneficiarioController($baseUrl, $basePath);
$eventoController = new EventoController($baseUrl, $basePath);
$relatorioController = new RelatorioController($baseUrl, $basePath);
$quizzController = new QuizzController($basePath);

$router->get('/_front/health', [$systemController, 'health']);
$router->get('/', [$legacyController, 'home']);
$router->get('/dashboard', [$legacyController, 'dashboard']);
$router->get('/login', [$legacyController, 'login']);
$router->post('/login', [$legacyController, 'login']);
$router->get('/logout', [$legacyController, 'logout']);
$router->post('/logout', [$legacyController, 'logout']);
$router->get('/perfil', [$adminController, 'perfil']);
$router->post('/perfil', [$adminController, 'perfil']);
$router->get('/crm', [$adminController, 'crm']);
$router->post('/crm/salvar', [$adminController, 'crmSalvar']);
$router->get('/atendimento', [$adminController, 'atendimento']);
$router->post('/atendimento/salvar', [$adminController, 'atendimentoSalvar']);
$router->get('/chamada', [$adminController, 'chamada']);
$router->get('/chamada/lista', [$adminController, 'chamadaLista']);
$router->get('/chamada/faltas', [$adminController, 'chamadaFaltas']);
$router->post('/chamada/salvar', [$adminController, 'chamadaSalvar']);
$router->get('/swot', [$adminController, 'swot']);
$router->get('/feriados', [$adminController, 'feriados']);
$router->post('/feriados', [$adminController, 'feriados']);
$router->get('/assinatura/pdf', [$adminController, 'assinaturaPdf']);
$router->post('/assinatura/pdf/preview', [$adminController, 'assinaturaPdfPreview']);
$router->post('/assinatura/pdf/finalizar', [$adminController, 'assinaturaPdfFinalizar']);
$router->get('/assinatura/pdf/validar', [$adminController, 'assinaturaPdfValidar']);
$router->get('/backup', [$adminController, 'backup']);
$router->get('/backup/dados', [$adminController, 'backupDados']);
$router->get('/alertas', [$adminController, 'alerta']);
$router->post('/alertas/salvar', [$adminController, 'alertaSalvar']);
$router->get('/projetos', [$adminController, 'projetos']);
$router->post('/projetos', [$adminController, 'projetos']);
$router->get('/matriculas/turma', [$adminController, 'matriculasTurma']);
$router->get('/matriculas/resultado', [$adminController, 'matriculasResultado']);
$router->post('/matriculas/cadastrar', [$adminController, 'matriculasCadastrar']);
$router->post('/matriculas/alterar', [$adminController, 'matriculasAlterar']);
$router->post('/matriculas/excluir', [$adminController, 'matriculasExcluir']);
$router->get('/matriculas/contrato', [$adminController, 'matriculasContrato']);
$router->get('/matriculas/contratos/turma', [$adminController, 'matriculasContratosTurma']);
$router->get('/matriculas/contratos/curso', [$adminController, 'matriculasContratosCurso']);
$router->get('/configuracoes', [$adminController, 'configuracoes']);
$router->get('/colaboradores', [$adminController, 'colaboradores']);
$router->post('/colaboradores', [$adminController, 'colaboradores']);
$router->get('/colaboradores/reset-senha', [$adminController, 'colaboradoresResetSenha']);
$router->get('/permissoes', [$adminController, 'permissoes']);
$router->post('/permissoes', [$adminController, 'permissoes']);
$router->get('/permissoes/paginas', [$adminController, 'permissaoPaginas']);
$router->post('/permissoes/paginas', [$adminController, 'permissaoPaginas']);
$router->get('/beneficiarios/cadastro', [$beneficiarioController, 'cadastro']);
$router->post('/beneficiarios/cadastro', [$beneficiarioController, 'cadastro']);
$router->get('/beneficiarios/lista', [$beneficiarioController, 'lista']);
$router->get('/beneficiarios/dados', [$beneficiarioController, 'dados']);
$router->get('/beneficiarios/aniversariantes', [$beneficiarioController, 'aniversariantes']);
$router->post('/beneficiarios/aniversariantes/dados', [$beneficiarioController, 'aniversariantesDados']);
$router->get('/beneficiarios/consulta-cpf', [$beneficiarioController, 'consultaCpf']);
$router->post('/beneficiarios/avaliar-vulnerabilidade-stream', [$beneficiarioController, 'avaliarVulnerabilidadeStream']);
$router->get('/cursos', [$academicoController, 'cursos']);
$router->post('/cursos/cadastrar', [$academicoController, 'cursosCadastrar']);
$router->post('/cursos/alterar', [$academicoController, 'cursosAlterar']);
$router->post('/cursos/excluir', [$academicoController, 'cursosExcluir']);
$router->get('/turmas', [$academicoController, 'turmas']);
$router->post('/turmas/cadastrar', [$academicoController, 'turmasCadastrar']);
$router->post('/turmas/alterar', [$academicoController, 'turmasAlterar']);
$router->post('/turmas/excluir', [$academicoController, 'turmasExcluir']);
$router->get('/matriculas', [$academicoController, 'matriculasListagem']);
$router->get('/matriculas/realizar', [$academicoController, 'matriculasRealizar']);
$router->get('/eventos/inscricao', [$eventoController, 'inscricao']);
$router->post('/eventos/inscricao', [$eventoController, 'cadastrarInscrito']);
$router->get('/eventos/inscricao/sucesso', [$eventoController, 'inscricaoSucesso']);
$router->get('/eventos/inscritos', [$eventoController, 'inscritos']);
$router->get('/eventos/inscritos/editar', [$eventoController, 'editarInscrito']);
$router->post('/eventos/inscritos/editar', [$eventoController, 'editarInscrito']);
$router->post('/eventos/inscritos/excluir', [$eventoController, 'excluirInscrito']);
$router->get('/eventos/verifica-email', [$eventoController, 'verificarEmail']);
$router->get('/relatorios/frequencia', [$relatorioController, 'frequencia']);
$router->get('/relatorios/personalizado', [$relatorioController, 'personalizado']);
$router->get('/relatorios/presenca-curso-turma', [$relatorioController, 'presencaCursoTurma']);
$router->get('/relatorios/matriculados', [$relatorioController, 'matriculados']);
$router->get('/relatorios/swot', [$relatorioController, 'swot']);
$router->get('/quizz/avaliacao-professor', [$quizzController, 'formulario']);
$router->post('/quizz/avaliacao-professor', [$quizzController, 'enviar']);
$router->get('/quizz/avaliacao-professor/sucesso', [$quizzController, 'sucesso']);
$router->get('/legacy/{path}', [$legacyController, 'legacy']);
