<?php
declare(strict_types=1);

use FrontEnd\Controllers\LegacyPageController;
use FrontEnd\Controllers\AcademicoController;
use FrontEnd\Controllers\AlertaController;
use FrontEnd\Controllers\AssinaturaController;
use FrontEnd\Controllers\AtendimentoController;
use FrontEnd\Controllers\BackupController;
use FrontEnd\Controllers\BiaController;
use FrontEnd\Controllers\BeneficiarioController;
use FrontEnd\Controllers\ChamadaController;
use FrontEnd\Controllers\CrmController;
use FrontEnd\Controllers\ColaboradorController;
use FrontEnd\Controllers\ConfiguracaoController;
use FrontEnd\Controllers\EventoController;
use FrontEnd\Controllers\FeriadoController;
use FrontEnd\Controllers\MatriculaController;
use FrontEnd\Controllers\PerfilController;
use FrontEnd\Controllers\PermissaoController;
use FrontEnd\Controllers\ProjetoController;
use FrontEnd\Controllers\RelatorioController;
use FrontEnd\Controllers\SwotController;
use FrontEnd\Controllers\SystemController;
use FrontEnd\Controllers\QuizzController;

$systemController = new SystemController();
$legacyController = new LegacyPageController($baseUrl, $basePath);
$academicoController = new AcademicoController($baseUrl, $basePath);
$crmController = new CrmController($basePath);
$colaboradorController = new ColaboradorController($basePath);
$configuracaoController = new ConfiguracaoController($basePath);
$atendimentoController = new AtendimentoController($basePath);
$perfilController = new PerfilController($basePath);
$permissaoController = new PermissaoController($basePath);
$backupController = new BackupController($basePath);
$biaController = new BiaController($basePath);
$alertaController = new AlertaController($basePath);
$beneficiarioController = new BeneficiarioController($baseUrl, $basePath);
$chamadaController = new ChamadaController($basePath);
$assinaturaController = new AssinaturaController($basePath);
$swotController = new SwotController($basePath);
$feriadoController = new FeriadoController($basePath);
$projetoController = new ProjetoController($basePath);
$matriculaController = new MatriculaController($basePath);
$eventoController = new EventoController($baseUrl, $basePath);
$relatorioController = new RelatorioController($baseUrl, $basePath);
$quizzController = new QuizzController($basePath);

$router->get('/_front/health', [$systemController, 'health']);
$router->get('/', [$legacyController, 'home']);
$router->get('/dashboard', [$legacyController, 'dashboard']);
$router->get('/login', [$legacyController, 'login']);
$router->post('/login', [$legacyController, 'login']);
$router->get('/esqueci-senha', [$legacyController, 'esqueciSenha']);
$router->post('/esqueci-senha', [$legacyController, 'esqueciSenha']);
$router->get('/logout', [$legacyController, 'logout']);
$router->post('/logout', [$legacyController, 'logout']);
$router->get('/confirma', [$legacyController, 'confirma']);
$router->post('/confirma', [$legacyController, 'confirma']);
$router->get('/assinaturadigital', [$legacyController, 'assinaturaDigital']);
$router->get('/paginas-footer', [$legacyController, 'paginasFooter']);
$router->get('/beberibe2025', [$legacyController, 'beberibe2025']);
$router->get('/perfil', [$perfilController, 'index']);
$router->post('/perfil', [$perfilController, 'index']);
$router->get('/crm', [$crmController, 'index']);
$router->post('/crm/salvar', [$crmController, 'salvar']);
$router->get('/atendimento', [$atendimentoController, 'index']);
$router->post('/atendimento/salvar', [$atendimentoController, 'salvar']);
$router->get('/chamada', [$chamadaController, 'tipo']);
$router->get('/chamada/lista', [$chamadaController, 'lista']);
$router->get('/chamada/faltas', [$chamadaController, 'faltas']);
$router->get('/chamada/lista/listTotalChamada.php', [$chamadaController, 'faltas']);
$router->post('/chamada/salvar', [$chamadaController, 'salvar']);
$router->get('/swot', [$swotController, 'index']);
$router->post('/swot', [$swotController, 'index']);
$router->get('/swot/swot', [$swotController, 'index']);
$router->post('/swot/swot', [$swotController, 'index']);
$router->get('/feriados', [$feriadoController, 'index']);
$router->post('/feriados', [$feriadoController, 'index']);
$router->get('/assinatura/pdf', [$assinaturaController, 'upload']);
$router->post('/assinatura/pdf', [$assinaturaController, 'upload']);
$router->get('/assinatura/pdf/pdf', [$assinaturaController, 'upload']);
$router->post('/assinatura/pdf/pdf', [$assinaturaController, 'upload']);
$router->post('/assinatura/pdf/preview', [$assinaturaController, 'preview']);
$router->post('/assinatura/pdf/finalizar', [$assinaturaController, 'finalizar']);
$router->get('/assinatura/pdf/validar', [$assinaturaController, 'validar']);
$router->get('/backup', [$backupController, 'configuracao']);
$router->get('/backup/dados', [$backupController, 'dados']);
$router->get('/bia', [$biaController, 'index']);
$router->post('/bia', [$biaController, 'index']);
$router->post('/bia/stream', [$biaController, 'stream']);
$router->post('/bia/reset', [$biaController, 'reset']);
$router->get('/alertas', [$alertaController, 'index']);
$router->post('/alertas/salvar', [$alertaController, 'salvar']);
$router->get('/projetos', [$projetoController, 'index']);
$router->post('/projetos', [$projetoController, 'index']);
$router->get('/matriculas/turma', [$matriculaController, 'turma']);
$router->get('/matriculas/resultado', [$matriculaController, 'resultado']);
$router->post('/matriculas/cadastrar', [$matriculaController, 'cadastrar']);
$router->post('/matriculas/alterar', [$matriculaController, 'alterar']);
$router->post('/matriculas/excluir', [$matriculaController, 'excluir']);
$router->get('/matriculas/contrato', [$matriculaController, 'contrato']);
$router->get('/matriculas/contratos/turma', [$matriculaController, 'contratosTurma']);
$router->post('/matriculas/contratos/turma/processar', [$matriculaController, 'contratosTurmaProcessar']);
$router->post('/matriculas/contratos/turma/solicitar', [$matriculaController, 'contratosTurmaSolicitar']);
$router->get('/matriculas/contratos/curso', [$matriculaController, 'contratosCurso']);
$router->post('/matriculas/contratos/curso', [$matriculaController, 'contratosCurso']);
$router->get('/configuracoes', [$configuracaoController, 'index']);
$router->post('/configuracoes', [$configuracaoController, 'index']);
$router->get('/colaboradores', [$colaboradorController, 'index']);
$router->post('/colaboradores', [$colaboradorController, 'index']);
$router->get('/colaboradores/reset-senha', [$colaboradorController, 'resetSenha']);
$router->post('/colaboradores/reset-senha', [$colaboradorController, 'resetSenha']);
$router->get('/permissoes', [$permissaoController, 'index']);
$router->post('/permissoes', [$permissaoController, 'index']);
$router->get('/permissoes/paginas', [$permissaoController, 'paginas']);
$router->post('/permissoes/paginas', [$permissaoController, 'paginas']);
$router->get('/beneficiarios/cadastro', [$beneficiarioController, 'cadastro']);
$router->post('/beneficiarios/cadastro', [$beneficiarioController, 'cadastro']);
$router->get('/beneficiarios/lista', [$beneficiarioController, 'lista']);
$router->get('/beneficiarios/dados', [$beneficiarioController, 'dados']);
$router->get('/beneficiarios/fotos', [$beneficiarioController, 'fotos']);
$router->get('/beneficiarios/aniversariantes', [$beneficiarioController, 'aniversariantes']);
$router->post('/beneficiarios/aniversariantes/dados', [$beneficiarioController, 'aniversariantesDados']);
$router->get('/beneficiarios/consulta-cpf', [$beneficiarioController, 'consultaCpf']);
$router->post('/beneficiarios/avaliar-vulnerabilidade-stream', [$beneficiarioController, 'avaliarVulnerabilidadeStream']);
$router->get('/cursos', [$academicoController, 'cursos']);
$router->get('/cursos/planejamento', [$academicoController, 'cursosPlanejamento']);
$router->get('/plano-cursos', [$academicoController, 'planoCursos']);
$router->post('/cursos/cadastrar', [$academicoController, 'cursosCadastrar']);
$router->post('/cursos/alterar', [$academicoController, 'cursosAlterar']);
$router->post('/cursos/excluir', [$academicoController, 'cursosExcluir']);
$router->get('/turmas', [$academicoController, 'turmas']);
$router->get('/turmas/cronograma', [$academicoController, 'turmasCronograma']);
$router->post('/turmas/cadastrar', [$academicoController, 'turmasCadastrar']);
$router->post('/turmas/alterar', [$academicoController, 'turmasAlterar']);
$router->post('/turmas/excluir', [$academicoController, 'turmasExcluir']);
$router->get('/matriculas', [$academicoController, 'matriculasListagem']);
$router->get('/matriculas/realizar', [$academicoController, 'matriculasRealizar']);
$router->post('/matriculas/realizar', [$academicoController, 'matriculasRealizar']);
$router->get('/eventos/inscricao', [$eventoController, 'inscricao']);
$router->post('/eventos/inscricao', [$eventoController, 'cadastrarInscrito']);
$router->get('/eventos/inscricao/sucesso', [$eventoController, 'inscricaoSucesso']);
$router->get('/eventos/inscritos', [$eventoController, 'inscritos']);
$router->get('/eventos/inscritos/editar', [$eventoController, 'editarInscrito']);
$router->post('/eventos/inscritos/editar', [$eventoController, 'editarInscrito']);
$router->post('/eventos/inscritos/excluir', [$eventoController, 'excluirInscrito']);
$router->get('/eventos/verifica-email', [$eventoController, 'verificarEmail']);
$router->get('/relatorios/frequencia', [$relatorioController, 'frequencia']);
$router->get('/relatorios/personalizado', [$relatorioController, 'personalizado']);
$router->get('/relatorios/presenca-curso-turma', [$relatorioController, 'presencaCursoTurma']);
$router->get('/relatorios/matriculados', [$relatorioController, 'matriculados']);
$router->get('/relatorios/swot', [$relatorioController, 'swot']);
$router->get('/relatorios/ficha-cadastro-pdf', [$relatorioController, 'fichaCadastroPdf']);
$router->post('/relatorios/ipai-anamnese-pdf', [$relatorioController, 'ipaiAnamnesePdf']);
$router->get('/quizz/avaliacao-professor', [$quizzController, 'formulario']);
$router->post('/quizz/avaliacao-professor', [$quizzController, 'enviar']);
$router->get('/quizz/avaliacao-professor/sucesso', [$quizzController, 'sucesso']);
$router->get('/legacy/{path}', [$legacyController, 'legacy']);
