CREATE TABLE IF NOT EXISTS tb_Cron_Contrato (
    IdCronContrato INT NOT NULL AUTO_INCREMENT,
    TipoReferencia VARCHAR(20) NOT NULL DEFAULT 'CURSO',
    IdCurso INT NULL,
    IdTurma INT NULL,
    NomeCurso VARCHAR(255) NULL,
    NomeTurma VARCHAR(255) NULL,
    EmailDestino VARCHAR(255) NOT NULL,
    Status TINYINT NOT NULL DEFAULT 1,
    TotalRegistros INT NOT NULL DEFAULT 0,
    Processados INT NOT NULL DEFAULT 0,
    NomeZip VARCHAR(255) NULL,
    CaminhoZip VARCHAR(500) NULL,
    UrlZip VARCHAR(500) NULL,
    TokenDownload VARCHAR(120) NULL,
    MensagemErro TEXT NULL,
    IdColaboradorSolicitante INT NULL,
    DataSolicitacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DataAtualizacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (IdCronContrato),
    KEY idx_tb_cron_contrato_status (Status),
    KEY idx_tb_cron_contrato_tipo (TipoReferencia),
    KEY idx_tb_cron_contrato_token (TokenDownload)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;